services:
  stadium-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_SERVER=10.120.0.19
      - DB_USER=Gonza
      - DB_PASSWORD=3NCUNTR4$
      - DB_DATABASE=VsStadium # To be confirmed
      - DB_INSTANCE= # To be confirmed
    restart: always
